set(_AMENT_PACKAGE_NAME "lab4_my_robot_gazebo")
set(lab4_my_robot_gazebo_VERSION "0.0.0")
set(lab4_my_robot_gazebo_MAINTAINER "omnia <omnia@todo.todo>")
set(lab4_my_robot_gazebo_BUILD_DEPENDS )
set(lab4_my_robot_gazebo_BUILDTOOL_DEPENDS "ament_cmake")
set(lab4_my_robot_gazebo_BUILD_EXPORT_DEPENDS )
set(lab4_my_robot_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(lab4_my_robot_gazebo_EXEC_DEPENDS )
set(lab4_my_robot_gazebo_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(lab4_my_robot_gazebo_GROUP_DEPENDS )
set(lab4_my_robot_gazebo_MEMBER_OF_GROUPS )
set(lab4_my_robot_gazebo_DEPRECATED "")
set(lab4_my_robot_gazebo_EXPORT_TAGS)
list(APPEND lab4_my_robot_gazebo_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
